stages:
  data_collection:
    cmd: python src/data_collection/scraper.py
    deps:
      - src/data_collection/scraper.py
    outs:
      - data/raw/reviews.csv
    metrics:
      - data/raw/collection_metrics.json:
          cache: false

  preprocessing:
    cmd: python src/preprocessing/preprocess.py
    deps:
      - src/preprocessing/preprocess.py
      - data/raw/reviews.csv
    outs:
      - data/processed/processed_reviews.csv
    params:
      - preprocessing.min_text_length
      - preprocessing.remove_stopwords
      - preprocessing.binary_classification

  training_bert:
    cmd: python src/training/train_bert.py
    deps:
      - src/training/train_bert.py
      - data/processed/processed_reviews.csv
    outs:
      - models/bert_model
    metrics:
      - models/bert_metrics.json:
          cache: false
    params:
      - training.bert_model
      - training.max_length
      - training.batch_size
      - training.epochs
      - training.learning_rate
      - training.test_size
      - training.random_state

  training_traditional:
    cmd: python src/training/train.py
    deps:
      - src/training/train.py
      - data/processed/processed_reviews.csv
    outs:
      - models/sentiment_model.pkl
      - models/vectorizer.pkl
    metrics:
      - models/metrics.json:
          cache: false
    plots:
      - models/confusion_matrix.png
    params:
      - training.model_type
      - training.test_size
      - training.random_state
      - training.max_features
      - training.ngram_range

